WHITESPACE = _{ " " | "\t" | "\n" | "\r" }
COMMENT = _{ "//" ~ (!"\n" ~ ANY)* }

KW_LET = _{ "let" }
KW_IF = _{ "if" }
KW_ELSE = _{ "else" }
KW_WHILE = _{ "while" }
KW_BREAK = _{ "break" }
KW_CONTINUE = _{ "continue" }
KW_FN = _{ "fn" }
KW_RETURN = _{ "return" }
KW_RECORD = _{ "record" }
KW_ENUM = _{ "enum" }

ident = @{ !(KW_LET | KW_IF | KW_ELSE | KW_WHILE | KW_BREAK | KW_CONTINUE | KW_FN | KW_RETURN | KW_ENUM | "record")
  ~ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }
int = @{ ASCII_DIGIT+ }
string = @{ "\"" ~ ( "\\\"" | "\\\\" | !"\"" ~ ANY )* ~ "\"" }
type_name = { array_type | "i32" | "u64" | "f64" | "bool" | "string" | "res" | ident }
array_type = { "[" ~ type_name ~ "]" }
field_decl = { ident ~ ":" ~ type_name }
record_decl = { "record" ~ ident ~ "{" ~ (field_decl ~ ("," ~ field_decl)*)? ~ ","? ~ "}" }
enum_field = { ident ~ ":" ~ type_name }
enum_variant = { ident ~ ("(" ~ (type_name ~ ("," ~ type_name)*)? ~ ")" | "{" ~ (enum_field ~ ("," ~ enum_field)*)? ~ "}")? }
enum_decl = { "enum" ~ ident ~ "{" ~ (enum_variant ~ ("," ~ enum_variant)*)? ~ ","? ~ "}" }

unary_op = { "-" | "!" }
record_field = { ident ~ ":" ~ expr }
record_name = @{ !("true" | "false") ~ ident }
enum_variant_expr = { ident ~ "::" ~ ident ~ ("{" ~ (record_field ~ ("," ~ record_field)*)? ~ ","? ~ "}")? }
record_expr = { record_name ~ "{" ~ (record_field ~ ("," ~ record_field)*)? ~ ","? ~ "}" }
field_access = { (call | ident | paren) ~ ("." ~ ident)+ }
array = { "[" ~ (expr ~ ("," ~ expr)*)? ~ ","? ~ "]" }
index_access = { (call | ident | paren | array) ~ ("[" ~ expr ~ "]")+ }
atom = _{ int | string | if_expr | match_expr | block | enum_variant_expr | record_expr | field_access | index_access | call | array | ident | paren }
call = { ident ~ "(" ~ (expr ~ ("," ~ expr)*)? ~ ")" }
paren = { "(" ~ expr ~ ")" }
expr = { term ~ (bin_op ~ term)* ~ "?"? }
term = { unary_op? ~ atom }
bin_op = _{ "+" | "-" | "*" | "/" | "&&" | "||" | "==" | "<" | ">" }
pattern = @{ "_" | ident ~ "::" ~ ident ~ ("{" ~ (ident ~ ("," ~ ident)*)? ~ "}")? | ("Ok" | "Err") ~ "(" ~ ident ~ ")" }
match_arm = { pattern ~ "=>" ~ expr }
match_expr = { "match" ~ expr ~ "{" ~ (match_arm ~ ("," ~ match_arm)*)? ~ ","? ~ "}" }

block = { "{" ~ stmt* ~ expr? ~ "}" }
if_stmt = { KW_IF ~ expr ~ block ~ (KW_ELSE ~ block)? }
if_expr = { KW_IF ~ expr ~ block ~ (KW_ELSE ~ block)? }
while_stmt = { KW_WHILE ~ expr ~ block }
break_stmt = { KW_BREAK ~ ";" }
continue_stmt = { KW_CONTINUE ~ ";" }
return_stmt = { KW_RETURN ~ expr? ~ ";" }
let_decl = { KW_LET ~ ident ~ (":" ~ type_name)? ~ "=" ~ expr ~ ";" }
assign_target = { ident ~ ("[" ~ expr ~ "]")+ }
assign = { assign_target ~ "=" ~ expr ~ ";" | ident ~ "=" ~ expr ~ ";" }
param = { ident ~ ":" ~ type_name }
fn_decl = { KW_FN ~ ident ~ "(" ~ (param ~ ("," ~ param)*)? ~ ")" ~ ("->" ~ type_name)? ~ block }
expr_stmt = { expr ~ ";" }
stmt = { enum_decl | record_decl | fn_decl | let_decl | assign | if_stmt | while_stmt | break_stmt | continue_stmt | return_stmt | expr_stmt }
program = { SOI ~ stmt* ~ EOI }
